### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by WenXin20** [Samarium150/StructuresCompass#8] opened 2021-07-12 02:32 UTC
`Minecraft v1.16.5`
`Forge v36.1.32`
`Structure's Compass v1.1.0`

When trying to check for a recipe for the compass while on my server, I noticed jei would not display it. Upon checking the server logs, I found this:
```
[net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe structurescompass:structures_compass_easy
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'structurescompass:recipe'
```

**Comment by Samarium150** [comment] 2021-07-14 02:14
Not sure why, and we cannot reproduce the error.

**Comment by WenXin20** [comment] 2021-07-14 02:33
Oh odd

**Comment by spthiel** [comment] 2021-07-17 09:48
Having the exact same issue.

Enviroment of testing:
forge-1.15.2-31.2.50.jar
minecraft_server.1.15.2.jar
structurecompass-1.15.2-1.1.0.jar
no other mods installed

The issue seems to be caused by the IRecipeType not being registered on Servers due to the limitation of the event to Client. (However allowing the event to also be executed on the server cases "Unknown recipe serializer minecraft:" and I gave up testing after that

**Comment by Samarium150** [comment] 2021-07-19 04:02
> Having the exact same issue.
> 
> Enviroment of testing:
> forge-1.15.2-31.2.50.jar
> minecraft_server.1.15.2.jar
> structurecompass-1.15.2-1.1.0.jar
> no other mods installed
> 
> The issue seems to be caused by the IRecipeType not being registered on Servers due to the limitation of the event to Client. (However allowing the event to also be executed on the server cases "Unknown recipe serializer minecraft:" and I gave up testing after that

I‘ve also reproduced this error, but I'm not sure why this happened.

**Comment by spthiel** [comment] 2021-07-19 05:16
What I can tell you is that when value = Dist.CLIENT is removed from [this line](https://github.com/Samarium150/StructuresCompass/blob/8ec3987ec083b7c3a577651014e16accb85cc388/src/main/java/com/github/samarium150/structurescompass/init/RecipeRegistry.java#L19), the mod correctly loads the recipe but causes an error when a client tries to join the server

**Comment by Samarium150** [comment] 2021-07-19 07:34
> What I can tell you is that when value = Dist.CLIENT is removed from [this line](https://github.com/Samarium150/StructuresCompass/blob/8ec3987ec083b7c3a577651014e16accb85cc388/src/main/java/com/github/samarium150/structurescompass/init/RecipeRegistry.java#L19), the mod correctly loads the recipe but causes an error when a client tries to join the server

Indeed, that's why the error confuses me.

**Comment by joe-vettek** [comment] 2021-07-26 07:59
It's the same with me,hope you can solve it.And when I check the recipe in JEI,it can cause to too long time for sever to wait and then crash.

**Comment by Samarium150** [comment] 2021-07-28 09:59
Still don't know why. Possible workaround: remove the easy or normal recipe which means the recipe will be fixed and there is no changeable option for it. If you feel comfortable with it, add :+1: reactions here, otherwise add :-1:

**Closed** 2021-07-29 00:22 UTC
Labels: bug
